splash = false

preload = /home/erkkisula/pics/wallpaper/catalina.jpg

wallpaper {
  monitor = eDP-1
  path = /home/erkkisula/pics/wallpaper/catalina.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/erkkisula/pics/wallpaper/catalina.jpg
  fit_mode = cover
}
